### ISSUE TITLE
Empty strings are not valid header values

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc#23]
Creating this to ensure implementations can verify consistency.

**Comment by breerly** [comment]
Don't we want to be loose in regards to headers? I can imagine this validation catching a lot of people

**Comment by abhinav** [comment]
Yeah, that's totally up for discussion. I don't feel strongly about either as long as we are consistent between languages.

Thoughts @yarpc/yarpc?

**Comment by kriskowal** [comment]
I suggest this guiding principle: We must enforce use of the subset that works for both HTTP and TChannel, and otherwise be as loose as possible. Empty header values are possible in all TChannel argument schemes and HTTP.

This principle settles other arguments:

- Headers must be case insensitive because HTTP headers are case insensitive.
- Headers must not contain duplicate keys because JSON over TChannel does not allow duplicate keys.

**Comment by breerly** [comment]
+1 - @kriskowal can you get that in a headers.md?

**Comment by kriskowal** [comment]
writing now.
