### ISSUE TITLE
RPC- request header prefix

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yarpc#38]
YARPC must take a request header prefix (and eventually a context header prefix). This is the prefix for the caller, service, procedure, and other request properties. The prefix must be configurable (for an organization to avoid a name collision) and the default must be `RPC-`.

We’ll slip this into the next milestone, `crossdock-headers`.

- [x] node
- [x] go
- [x] python
- [x] java

**Comment by breerly** [comment]
I think YARPC should continue to default to `YARPC-` as the header prefix - but should allow us to reconfigure that prefix to `RPC-`

**Comment by abhinav** [comment]
-1 on configurable prefixes. That adds yet another discrepancy that different clients have to be aware about. We will almost most certainly see issues where different clients are using different prefixes and their requests are failing.

**Comment by breerly** [comment]
Then the prefix should be `YARPC-` - we don't want to presume to take that namespace for the entire internet.

**Comment by abhinav** [comment]
I'm okay with the YARPC prefix. If a system needs to interact with YARPC requests at the HTTP level, they have to use whatever prefix our spec says we're sending.

**Comment by prashantv** [comment]
-1 for YARPC. It's basically tying a bunch of other unrelated infrastructure and tooling to YARPC.
E.g. I have a PR for tbench that "knows" about YARPC
https://github.com/uber/tbench/pull/8/files#diff-2d08121c527972df0fc40641b3ecc1a2R88

I don't want to make the user specify a "YARPC" prefix everytime they use it against YARPC, but it's also strange to have it tied to the YARPC namespace.

YARPC decouples us from the underlying protocol/serialization, similarly, our other infrastructure should also be decoupled from knowing about YARPC specifically. I like RPC since it's a pretty generic prefix.

Agree with @breerly  that if it's `RPC-`, it would need to be configurable. In terms of configurable prefixes, I don't think these would be set on a per-service basis, but on a per-organization basis.

**Comment by breerly** [comment]
Option 3:

1. YARPC uses the `RPC-` prefix by default - (because we are prestigious)
2. You CAN reconfigure this if needed.
3. We don't reconfigure it.

It's sort of a bad practice to claim a generic top-level header space like this, but :shrug:

**Comment by breerly** [comment]
Sounds like Option 3 has reached enough consensus. @kriskowal can you update the ticket description to reflect?

**Comment by breerly** [comment]
This is done 🎉
